CREATE TABLE NIVEL (
	CODIGONIVEL int NOT NULL,
	Descricao VARCHAR (90) NOT NULL,
	CONSTRAINT CHAVEPNIVEL PRIMARY KEY (CODIGONIVEL)
);

CREATE TABLE CURSO (
	CODIGOCURSO int NOT NULL,
	Nome VARCHAR (90) NOT NULL UNIQUE,
	DataCriacao DATE NULL,
	CODIGONIVEL int NULL,
	CONSTRAINT CHAVEPCURSO PRIMARY KEY (CODIGOCURSO),
	FOREIGN KEY (CODIGONIVEL) REFERENCES NIVEL (CODIGONIVEL)
);

ALTER TABLE CURSO ADD DataFinalizacao DATE;  -- Adicionar coluna

ALTER TABLE CURSO DROP DataFinalizacao; -- Apagar coluna

DROP TABLE CURSO -- Apagar Tabela
